import subprocess
import json
import time
from  guidance import models,gen ,select

# 函数用于运行模型，并返回预测结果和时延
def run_model_json(model_name, input_text, expected_emotion):
    print(f"\n正在尝试运行模型: {model_name}")
    try:
        # 构建用于生成情感的提示
        # 构建用于生成情感的提示，只需要标签
        prompt = f"输入: {input_text}\n请只返回唯一答案，不要任何的多余文字,不要任何的符号，包括‘’,'',[]。"
        # prompt = f"输入: {input_text}\n请只返回情感标签：['喜悦', '悲伤', '生气', '恐惧', '惊讶', '厌恶'],不要任何的符号，包括‘’,'',[]。"

        # 然后使用 guidance 控制生成
        guidance_program = prompt + select(["喜悦", "悲伤", "生气", "恐惧", "惊讶", "厌恶"], name="emotion")

        # 这样可以让模型只返回你期望的情感标签
        # 记录开始时间
        start_time = time.time()

        # 使用subprocess运行ollama的命令
        process = subprocess.Popen(
            ["ollama", "run", model_name],
            stdin=subprocess.PIPE,  # 使用标准输入
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )

        # 将提示内容传入标准输入
        stdout, stderr = process.communicate(input=prompt.encode())

        # 记录结束时间
        end_time = time.time()
        latency = end_time - start_time

        # 解析模型返回的输出
        output = stdout.decode().strip()
        if not output:
            raise Exception(f"模型运行错误: {stderr.decode().strip()}")

        # 打印错误输出（用于调试）
        # print(f"标准输出: {stdout.decode()}")
        # print(f"错误输出: {stderr.decode()}")

        # 假设输出格式为单个情感标签
        predicted_emotion = output.strip()
        result = subprocess.Popen(['ollama', 'run', model_name], stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE, text=True,encoding='utf-8')
        output, error = result.communicate(input_text)

        # 构建JSON响应
        response_json = {
            "input": input_text,
            "predicted_emotion": predicted_emotion,
            "expected_emotion": expected_emotion,
            "latency": f"{latency:.4f}s"
        }
        print(json.dumps(response_json, ensure_ascii=False, indent=2))

        # 检查预测是否正确
        is_correct = predicted_emotion == expected_emotion
        return response_json, is_correct, latency

    except Exception as e:
        print(f"模型运行错误: {e}")
        return None, False, 0


# 示例数据集
dataset = [
    {"input": "哈哈哈，好可爱啊", "expected_emotion": "喜悦"},
    {"input": "这太让人失望了", "expected_emotion": "悲伤"},
    {"input": "你怎么能这样做？太过分了", "expected_emotion": "生气"},
    {"input": "你怎么能这样做？太过分了", "expected_emotion": "生气"},
    {"input": "我终于成功了，真是太棒了！", "expected_emotion": "喜悦"},
    {"input": "他竟然背叛了我，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻！", "expected_emotion": "生气"},
    {"input": "今天的天气真好，心情也跟着愉快起来", "expected_emotion": "喜悦"},
    {"input": "考试没考好，我感到很沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到孩子们的笑脸，我感到无比幸福", "expected_emotion": "喜悦"},
    {"input": "失去亲人的痛苦让我无法释怀", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不负责任了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我忍不住笑了起来", "expected_emotion": "喜悦"},
    {"input": "遭遇挫折，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的风景，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "哈哈哈，好可爱啊", "expected_emotion": "喜悦"},
    {"input": "这太让人失望了", "expected_emotion": "悲伤"},
    {"input": "你怎么能这样做？太过分了", "expected_emotion": "生气"},
    {"input": "我终于成功了，真是太棒了！", "expected_emotion": "喜悦"},
    {"input": "他竟然背叛了我，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻！", "expected_emotion": "生气"},
    {"input": "今天的天气真好，心情也跟着愉快起来", "expected_emotion": "喜悦"},
    {"input": "考试没考好，我感到很沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到孩子们的笑脸，我感到无比幸福", "expected_emotion": "喜悦"},
    {"input": "失去亲人的痛苦让我无法释怀", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不负责任了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我忍不住笑了起来", "expected_emotion": "喜悦"},
    {"input": "遭遇挫折，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的风景，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小猫玩耍，我感到非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去朋友让我感到非常伤心", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不公平了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常高兴", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "哈哈哈，好可爱啊", "expected_emotion": "喜悦"},
    {"input": "这太让人失望了", "expected_emotion": "悲伤"},
    {"input": "你怎么能这样做？太过分了", "expected_emotion": "生气"},
    {"input": "我终于成功了，真是太棒了！", "expected_emotion": "喜悦"},
    {"input": "他竟然背叛了我，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻！", "expected_emotion": "生气"},
    {"input": "今天的天气真好，心情也跟着愉快起来", "expected_emotion": "喜悦"},
    {"input": "考试没考好，我感到很沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到孩子们的笑脸，我感到无比幸福", "expected_emotion": "喜悦"},
    {"input": "失去亲人的痛苦让我无法释怀", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太不负责任了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我忍不住笑了起来", "expected_emotion": "喜悦"},
    {"input": "遭遇挫折，我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的风景，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "你这样做简直不可理喻，我真的很生气", "expected_emotion": "生气"},
    {"input": "听到朋友的鼓励，我感到非常开心", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常难过", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我再也不会原谅你", "expected_emotion": "生气"},
    {"input": "看到小动物的可爱模样，我忍不住笑了", "expected_emotion": "喜悦"},
    {"input": "失去朋友的信任让我感到非常痛苦", "expected_emotion": "悲伤"},
    {"input": "你这样做真是太自私了！", "expected_emotion": "生气"},
    {"input": "听到好消息，我感到非常兴奋", "expected_emotion": "喜悦"},
    {"input": "遭遇失败，我感到非常沮丧", "expected_emotion": "悲伤"},
    {"input": "你太过分了，我真的很生气", "expected_emotion": "生气"},
    {"input": "看到美丽的花朵，心情变得非常愉快", "expected_emotion": "喜悦"},
    {"input": "失去工作让我感到非常失落", "expected_emotion": "悲伤"},
    {"input": "我今天在超市看到一个人在吃生洋葱，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我的手机突然自己关机了，然后又自动开机了，真是不可思议！", "expected_emotion": "惊讶"},
    {"input": "我刚刚在公园里看到一只猫在和狗玩耍，这真是太罕见了！", "expected_emotion": "惊讶"},
    {"input": "我的电脑屏幕突然变成了彩虹色，这真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在路上看到一个人在倒着走路，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我刚刚在餐厅里看到一个人在吃辣椒酱拌饭，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在地铁上看到一个人在读一本全是数字的书，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我刚刚在公园里看到一个人在用脚写字，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在超市看到一个人在吃生大蒜，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我的手机突然自己关机了，然后又自动开机了，真是不可思议！", "expected_emotion": "惊讶"},
    {"input": "我刚刚在公园里看到一只猫在和狗玩耍，这真是太罕见了！", "expected_emotion": "惊讶"},
    {"input": "我的电脑屏幕突然变成了彩虹色，这真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在路上看到一个人在倒着走路，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我刚刚在餐厅里看到一个人在吃辣椒酱拌饭，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在地铁上看到一个人在读一本全是数字的书，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我刚刚在公园里看到一个人在用脚写字，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在超市看到一个人在吃生大蒜，真是太奇怪了！", "expected_emotion": "惊讶"},
    {"input": "我今天在地铁上闻到了一股难闻的气味，真是让人恶心！", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合随地吐痰，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在餐厅里看到一只苍蝇在食物上飞来飞去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声喧哗，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在路上看到一个人随地扔垃圾，真是让人恶心。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合吸烟，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在超市里看到一个人在挑选水果时用手捏来捏去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声打电话，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在公交车上闻到了一股难闻的气味，真是让人恶心！", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合随地吐痰，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在餐厅里看到一只苍蝇在食物上飞来飞去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声喧哗，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在路上看到一个人随地扔垃圾，真是让人恶心。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合吸烟，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在超市里看到一个人在挑选水果时用手捏来捏去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声打电话，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在地铁上闻到了一股难闻的气味，真是让人恶心！", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合随地吐痰，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在餐厅里看到一只苍蝇在食物上飞来飞去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声喧哗，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在路上看到一个人随地扔垃圾，真是让人恶心。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合吸烟，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在超市里看到一个人在挑选水果时用手捏来捏去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声打电话，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在公交车上闻到了一股难闻的气味，真是让人恶心！", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合随地吐痰，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在餐厅里看到一只苍蝇在食物上飞来飞去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声喧哗，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在路上看到一个人随地扔垃圾，真是让人恶心。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合吸烟，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在超市里看到一个人在挑选水果时用手捏来捏去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声打电话，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在地铁上闻到了一股难闻的气味，真是让人恶心！", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合随地吐痰，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在餐厅里看到一只苍蝇在食物上飞来飞去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声喧哗，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在路上看到一个人随地扔垃圾，真是让人恶心。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合吸烟，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在超市里看到一个人在挑选水果时用手捏来捏去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声打电话，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在公交车上闻到了一股难闻的气味，真是让人恶心！", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合随地吐痰，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在餐厅里看到一只苍蝇在食物上飞来飞去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声喧哗，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我今天在路上看到一个人随地扔垃圾，真是让人恶心。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合吸烟，我感到非常厌恶。", "expected_emotion": "厌恶"},
    {"input": "我刚刚在超市里看到一个人在挑选水果时用手捏来捏去，真是令人作呕。", "expected_emotion": "厌恶"},
    {"input": "看到有人在公共场合大声打电话，我感到非常厌恶。", "expected_emotion": "厌恶"}
]


# 选择模型名称
model_name = "llama3:latest"

# 评估模型
correct = 0
total_latency = 0
for sample in dataset:
    response, is_correct, latency = run_model_json(model_name, sample["input"], sample["expected_emotion"])
    if is_correct:
        correct += 1
    total_latency += latency

# 计算准确率和平均时延
accuracy = correct / len(dataset) * 100
average_latency = total_latency / len(dataset)
print(f"准确率: {accuracy:.2f}%")
print(f"平均时延: {average_latency:.4f}s")
